@extends('cms.layouts.app')
@section('title','Branding & Logo')
@push('styles')<style>.brand-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px;align-items:start}.brand-card{padding:22px;min-width:0}.brand-card h2{font-size:18px;margin:0 0 5px}.brand-card>p{color:var(--muted);min-height:42px;margin:0 0 18px}.brand-current{height:112px;background:#f5f6f7;border:1px solid var(--line);border-radius:12px;display:grid;place-items:center;margin-bottom:14px;overflow:hidden;padding:12px}.brand-current img{max-width:82%;max-height:82%;object-fit:contain}.brand-empty{color:#9aa0a8;text-align:center}.brand-card .upload-zone{grid-template-columns:58px minmax(0,1fr);min-height:132px}.brand-card .upload-preview{width:58px;height:58px}.remove-option{display:flex;gap:8px;align-items:center;color:#a32a23;margin-top:12px;font-size:12px}.branding-actions{margin-top:18px;display:flex;justify-content:flex-end}@media(max-width:720px){.brand-grid{grid-template-columns:1fr}.brand-card>p{min-height:0}.brand-card .upload-zone{grid-template-columns:1fr;text-align:center}.brand-card .upload-preview{margin:auto}}</style>@endpush
@section('content')
<div class="page-head"><div><h1>Branding & Logo</h1><p>Semua identitas visual website dikelola dari halaman ini.</p></div></div>
<form method="post" action="{{ route('cms.branding.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="brand-grid">
 <section class="card brand-card"><h2>Logo Frontend</h2><p>Tampil di header halaman website publik.</p><div class="brand-current">@if($branding['frontend_logo']??null)<img src="{{ $branding['frontend_logo'] }}" alt="Logo frontend saat ini">@else<span class="brand-empty">Menggunakan logo bawaan template</span>@endif</div>@include('cms.partials.upload',['name'=>'frontend_logo','accept'=>'image/*,.svg','title'=>'Upload logo frontend','hint'=>'PNG, WebP, SVG · maks. 5 MB','current'=>$branding['frontend_logo']??null])@if($branding['frontend_logo']??null)<label class="remove-option"><input type="checkbox" name="remove_frontend_logo" value="1"> Kembalikan ke logo bawaan</label>@endif</section>
 <section class="card brand-card"><h2>Logo CMS</h2><p>Tampil di sidebar dan halaman login CMS.</p><div class="brand-current">@if($branding['cms_logo']??null)<img src="{{ $branding['cms_logo'] }}" alt="Logo CMS saat ini">@else<span class="brand-empty">Menggunakan monogram DMC PRO</span>@endif</div>@include('cms.partials.upload',['name'=>'cms_logo','accept'=>'image/*,.svg','title'=>'Upload logo CMS','hint'=>'PNG, WebP, SVG · maks. 5 MB','current'=>$branding['cms_logo']??null])@if($branding['cms_logo']??null)<label class="remove-option"><input type="checkbox" name="remove_cms_logo" value="1"> Kembalikan ke logo bawaan</label>@endif</section>
 <section class="card brand-card"><h2>Favicon</h2><p>Ikon kecil pada tab browser frontend dan CMS.</p><div class="brand-current">@if($branding['favicon']??null)<img src="{{ $branding['favicon'] }}" alt="Favicon saat ini">@else<span class="brand-empty">Menggunakan favicon bawaan template</span>@endif</div>@include('cms.partials.upload',['name'=>'favicon','accept'=>'.ico,image/png,image/webp,image/svg+xml','title'=>'Upload favicon','hint'=>'ICO, PNG, WebP, SVG · maks. 2 MB','current'=>$branding['favicon']??null])@if($branding['favicon']??null)<label class="remove-option"><input type="checkbox" name="remove_favicon" value="1"> Kembalikan ke favicon bawaan</label>@endif</section>
</div><div class="branding-actions"><button class="button button-primary" type="submit">Simpan branding</button></div></form>
@endsection
